[package]
name = "iblocklist_generator"
version = "0.1.0"
authors = ["ali <github@alihong.net>"]
edition = "2018"

[dependencies]
flate2 = "1.0"
regex = "1"
surf = "2.1.0"
async-std = { version = "1.9.0", features = ["attributes", "unstable"] }
futures = "0.3.12"
