[package]
name = "iblocklist_generator"
version = "0.1.0"
authors = ["ali <github@alihong.net>"]
edition = "2021"

[dependencies]
flate2 = "1.0"
regex = "1"
futures = "0.3.12"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
bytes = "1.2.1"
